#############################################################################
# Makefile for building: qalambury
# Generated by qmake (2.01a) (Qt 4.7.1) on: wt. mar 1 18:37:40 2011
# Project:  qalambury.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qalambury.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qgraphicsviewplus.cpp \
		socketthread.cpp \
		logindialog.cpp \
		command.cpp \
		qlistwidgetplus.cpp moc_mainwindow.cpp \
		moc_qgraphicsviewplus.cpp \
		moc_socketthread.cpp \
		moc_logindialog.cpp \
		moc_qlistwidgetplus.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qgraphicsviewplus.o \
		socketthread.o \
		logindialog.o \
		command.o \
		qlistwidgetplus.o \
		moc_mainwindow.o \
		moc_qgraphicsviewplus.o \
		moc_socketthread.o \
		moc_logindialog.o \
		moc_qlistwidgetplus.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		qalambury.pro
QMAKE_TARGET  = qalambury
DESTDIR       = 
TARGET        = qalambury

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_logindialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qalambury.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile qalambury.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qalambury.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qalambury1.0.0 || $(MKDIR) .tmp/qalambury1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qalambury1.0.0/ && $(COPY_FILE) --parents mainwindow.h qgraphicsviewplus.h socketthread.h logindialog.h command.h qlistwidgetplus.h qtrio.h .tmp/qalambury1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp qgraphicsviewplus.cpp socketthread.cpp logindialog.cpp command.cpp qlistwidgetplus.cpp .tmp/qalambury1.0.0/ && $(COPY_FILE) --parents mainwindow.ui logindialog.ui .tmp/qalambury1.0.0/ && (cd `dirname .tmp/qalambury1.0.0` && $(TAR) qalambury1.0.0.tar qalambury1.0.0 && $(COMPRESS) qalambury1.0.0.tar) && $(MOVE) `dirname .tmp/qalambury1.0.0`/qalambury1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qalambury1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qgraphicsviewplus.cpp moc_socketthread.cpp moc_logindialog.cpp moc_qlistwidgetplus.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qgraphicsviewplus.cpp moc_socketthread.cpp moc_logindialog.cpp moc_qlistwidgetplus.cpp
moc_mainwindow.cpp: socketthread.h \
		command.h \
		logindialog.h \
		qtrio.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_qgraphicsviewplus.cpp: qgraphicsviewplus.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qgraphicsviewplus.h -o moc_qgraphicsviewplus.cpp

moc_socketthread.cpp: command.h \
		socketthread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) socketthread.h -o moc_socketthread.cpp

moc_logindialog.cpp: qtrio.h \
		logindialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) logindialog.h -o moc_logindialog.cpp

moc_qlistwidgetplus.cpp: qlistwidgetplus.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qlistwidgetplus.h -o moc_qlistwidgetplus.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_logindialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_logindialog.h
ui_mainwindow.h: mainwindow.ui \
		qgraphicsviewplus.h \
		qlistwidgetplus.h
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_logindialog.h: logindialog.ui
	/usr/bin/uic logindialog.ui -o ui_logindialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		socketthread.h \
		command.h \
		logindialog.h \
		qtrio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		socketthread.h \
		command.h \
		logindialog.h \
		qtrio.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qgraphicsviewplus.o: qgraphicsviewplus.cpp qgraphicsviewplus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qgraphicsviewplus.o qgraphicsviewplus.cpp

socketthread.o: socketthread.cpp socketthread.h \
		command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o socketthread.o socketthread.cpp

logindialog.o: logindialog.cpp logindialog.h \
		qtrio.h \
		ui_logindialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logindialog.o logindialog.cpp

command.o: command.cpp command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o command.o command.cpp

qlistwidgetplus.o: qlistwidgetplus.cpp qlistwidgetplus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qlistwidgetplus.o qlistwidgetplus.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qgraphicsviewplus.o: moc_qgraphicsviewplus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qgraphicsviewplus.o moc_qgraphicsviewplus.cpp

moc_socketthread.o: moc_socketthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_socketthread.o moc_socketthread.cpp

moc_logindialog.o: moc_logindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logindialog.o moc_logindialog.cpp

moc_qlistwidgetplus.o: moc_qlistwidgetplus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qlistwidgetplus.o moc_qlistwidgetplus.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

